version: "3.7"

services:
  appgc:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./public:/usr/src/app/public
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_HTTPS=false
      - NEXT_PUBLIC_PWA=true
    depends_on:
      - postgresgc
      - miniogc
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 15s
      retries: 3
    networks:
      - greencrowd

  postgresgc:
    image: postgres:15.3
    container_name: postgresgc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d greencrowd"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - greencrowd

  miniogc:
    container_name: miniogc
    image: minio/minio:RELEASE.2024-04-28T17-53-50Z
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - greencrowd

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
      - ./public:/usr/share/nginx/html/public
    networks:
      - greencrowd

volumes:
  minio_data:
  postgres_data:

networks:
  greencrowd:
    external: true
