version: "3.7"

services:
  postgresgc_prod:
    image: postgres:15.3
    container_name: postgresgc_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d greencrowd"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - greencrowd

volumes:
  minio_prod_data:
  postgres_prod_data:

networks:
  greencrowd:
    external: true
