name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Get Git commit hash
        id: commit
        run: echo "GIT_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          build-args: |
            TARGET=prod
            GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}
          push: true
          tags: |
            fvergaracl/greencrowd:latest
            fvergaracl/greencrowd:${{ github.ref_name }}.${{ env.date }}
            fvergaracl/greencrowd:commit-${{ env.GIT_COMMIT_HASH }}
